.TH "ble_cus_evt_t" 3 "Fri Jul 24 2020" "BLE SWITCH (REMOTE) APPLICATION" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ble_cus_evt_t \- Custom Service event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ble_cus_p\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBble_cus_evt_type_t\fP \fBevt_type\fP"
.br
.ti -1c
.RI "uint16_t \fBconn_handle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Custom Service event\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t conn_handle"
Custom Service event type\&. 
.SS "\fBble_cus_evt_type_t\fP evt_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for BLE SWITCH (REMOTE) APPLICATION from the source code\&.
