.TH "ble_cus_init_t" 3 "Fri Jul 24 2020" "BLE SWITCH (REMOTE) APPLICATION" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ble_cus_init_t \- custom Service init structure\&. This contains all options and data needed for initialization of the service\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ble_cus_p\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBble_cus_evt_handler_t\fP \fBevt_handler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
custom Service init structure\&. This contains all options and data needed for initialization of the service\&. 
.SH "Field Documentation"
.PP 
.SS "\fBble_cus_evt_handler_t\fP evt_handler"


.SH "Author"
.PP 
Generated automatically by Doxygen for BLE SWITCH (REMOTE) APPLICATION from the source code\&.
