.TH "custom_service Directory Reference" 3 "Fri Jul 24 2020" "BLE SWITCH (REMOTE) APPLICATION" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_service Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBble_cus_p\&.c\fP"
.br
.ti -1c
.RI "file \fBble_cus_p\&.h\fP"
.br
.RI "This module implements a custom Button Service with an Button(Touch Switch) Characteristics\&. During initialization, the module adds the Custom Button Service and Characteristics to the BLE stack database\&. "
.in -1c
