.TH "custom_service Directory Reference" 3 "Wed Jul 22 2020" "BLE SWITCH (REMOTE) APPLICATION" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_service Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBble_cus_p\&.c\fP"
.br
.ti -1c
.RI "file \fBble_cus_p\&.h\fP"
.br
.in -1c
